services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - '80:5173'
    depends_on:
      - backend
    env_file:
      - .env
      - ./frontend/.env
